# Generated by Django 2.2.13 on 2020-10-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfiles',
            name='file_path',
            field=models.URLField(default='urls..'),
            preserve_default=False,
        ),
    ]
